FaceFind/Controllers/ImageController.cs
using FaceFind.Bll;
using FaceFind.Entities;
using FaceFind.Filters;
using FaceFind.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaceFind.Controllers
{
    /// <summary>
    /// Содержит основные операции с фотографиями
    /// </summary>
    public class ImageController : Controller
    {
        private IApplicationLogic logic;

        /// <summary>
        /// Метод проверяет, является ли загруженный файл изображением
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        private bool IsImage(HttpPostedFileBase file)
        {
            if(file == null)
            {
                return false;
            }
            if (file.ContentType.Contains("image"))
            {
                return true;
            }

            string[] formats = new string[] { ".jpg", ".png", ".gif", ".jpeg" };

            return formats.Any(item => file.FileName.EndsWith(item, StringComparison.OrdinalIgnoreCase));
        }
        public ImageController()
        {
            logic = new ApplicationLogic();
        }
        /// <summary>
        /// Возвращает страницу загрузки фотографии
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles =Role.SuperAdminRoleTitle + ", " + Role.AdminRoleTitle + ", " + Role.UserRoleTitle)]
        public ActionResult UploadImage()
        {
            return View();
        }
        /// <summary>
        /// Загружает полученную фотографию в профиль текущего пользователя
        /// </summary>
        /// <param name="image"></param>
        /// <returns></returns>
        [Authorize(Roles =Role.SuperAdminRoleTitle + ", " + Role.AdminRoleTitle + ", " + Role.UserRoleTitle)]
        [HttpPost]
        public ActionResult UploadImage(HttpPostedFileBase image)
        {
            if (IsImage(image))
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    image.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                    Photo photo = new Photo();
                    photo.Content = array;
                    photo.ContentType = image.ContentType;
                    logic.AddOrChangePhoto(photo, User.Identity.Name);
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ViewBag.Error = "Загруженный файл не является изображением";
                return View();
            }

        }
        /// <summary>
        /// Отображает фотографию пользователя по id его личных данных
        /// </summary>
        /// <param name="personId"></param>
        /// <returns></returns>
        [Authorize(Roles =Role.SuperAdminRoleTitle + ", " + Role.AdminRoleTitle + ", " + Role.UserRoleTitle)]
        public ActionResult DisplayUserImage(Guid personId)
        {
            var person = logic.GetPersonByPersonId(personId);
            if (person.Photo == null)
            {
                return File("~/Content/Images/placeholder.jpg", "image/jpeg");
            }
            return File(person.Photo.Content, person.Photo.ContentType);
        }
    }
}

FaceFind/Controllers/MessagesController.cs
using FaceFind.Bll;
using FaceFind.Entities;
using FaceFind.Filters;
using FaceFind.Models;
using FaceFindBll.Interfaces;
using FaceFindBll.Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaceFind.Controllers
{
    [Authorize, DenyAuthorized(Roles = Role.BannedRoleTitle)]
    public class MessagesController : Controller
    {
        private IMessagesLogic logic;


        public MessagesController()
        {
            logic = new MessagesLogic();
        }

        public ActionResult Dialogs()
        {
            var dialogs = logic.GetUserDialogs(User.Identity.Name);
            var currentUser = logic.GetPersonByUserLogin(User.Identity.Name);
            var res = new List<DialogVM>();
            foreach (var item in dialogs)
            {
                res.Add(new DialogVM(item, currentUser.Id));
            }
            return View(res);
        }

        public ActionResult Dialog(Guid DialogId)
        {
            var dialog = logic.GetUserDialog(User.Identity.Name, DialogId);
            var res = new List<MessageVM>();
            foreach (var item in dialog)
            {
                res.Add(new MessageVM(item));
            }
            ViewBag.DialogId = DialogId;
            return View(res);
        }

        public ActionResult OpenDialog(Guid personId)
        {

            Guid dialogId = logic.GetDialogId(personId, User.Identity.Name);
            return RedirectToAction("Dialog", new { DialogId = dialogId });
        }

        [HttpPost]
        public ActionResult SendMessage(Guid DialogId, string Content)
        {
            var msg = new Message(Content);
            var current = logic.GetPersonByUserLogin(User.Identity.Name);
            msg.From = current;
            logic.SendMessage(msg, DialogId);

            var msgVM = new MessageVM(msg);
            return PartialView(msgVM);
        }
    }
}

FaceFind/Views/Messages/Dialog.cshtml
@model IEnumerable<FaceFind.Models.MessageVM>

@{
    ViewBag.Title = "Dialog";
}
<h2>
    Диалог
</h2>
<div>
    @using (Ajax.BeginForm("SendMessage", "Messages", new AjaxOptions() { HttpMethod = "POST", InsertionMode = InsertionMode.InsertBefore, UpdateTargetId = "ins" }))
    {
        <input type="text" name="Content" id="sendContent" />
        <input type="hidden" name="DialogId" value="@ViewBag.DialogId" />
        <button type="submit" id="sendBtn" class="btn btn-primary">Отправить</button>
    }
</div>
<div id="ins">
    @foreach (var item in Model)
    {
        <div class="message row">
            <div class="col-xs-3">
                <a href="@Url.Action("GetPerson", "Home", new { personId = item.SenderID })">
                    <img class="avatar-small" src="@Url.Action("DisplayUserImage", "Image", new { personId = item.SenderID }) " />
                    <i>@item.Name</i>
                </a>
            </div>
            <div class="col-xs-7">
                <span>@item.Content</span>
            </div>
            <div class="col-xs-2">
                @string.Format("{0} {1}", item.SendDate.ToShortDateString(), item.SendDate.ToShortTimeString())
            </div>
        </div>
    }
</div>
@section Scripts {
    <script src="~/Scripts/Site/DialogsActions.js"></script>
}

FaceFind/Views/Messages/Dialogs.cshtml
@model IEnumerable<FaceFind.Models.DialogVM>

@{
    ViewBag.Title = "Dialogs";
}

@if (Model.Count() == 0)
{
    <h2>
        Тут пока ничего нет...
    </h2>
}
else
{
    <h2>
        Сообщения
    </h2>
    <table class="table">
        @foreach (var item in Model)
        {
            <tr data-id="@item.ID" class="dialog">
                <td>
                    <a href="@Url.Action("GetPerson", "Home", new { personId = item.ReceiverID })">
                        <img class="avatar-small" src="@Url.Action("DisplayUserImage", "Image", new { personId = item.ReceiverID }) " />
                        <i>@item.ReceiverName @item.ReceiverSurname</i>
                    </a>
                </td>
                @if (item.LastMessage != null)
                {
                    <td>

                        <span>
                            <img class="avatar-small" src="@Url.Action("DisplayUserImage", "Image", new { personId = item.LastMessage.From.Id }) " />
                        </span>
                        <span>
                            @item.LastMessage.Content
                        </span>

                    </td>
                    <td>
                        @item.LastMessage.SendDate.ToShortDateString() @item.LastMessage.SendDate.ToShortTimeString()
                    </td>
                }
                else
                {
                    <td colspan="2"><i>нет сообщений</i></td>
                }
            </tr>
        }

    </table>
}

@section Scripts{
    <script src="~/Scripts/Site/DialogsActions.js"></script>
}

FaceFind/Views/Messages/SendMessage.cshtml
@model FaceFind.Models.MessageVM
<div class="message row">
    <div class="col-xs-3">
        <a href="@Url.Action("GetPerson", "Home", new { personId = Model.SenderID })">
            <img class="avatar-small" src="@Url.Action("DisplayUserImage", "Image", new { personId = Model.SenderID }) " />
            <i>@Model.Name</i>
        </a>
    </div>
    <div class="col-xs-7">
        <span>@Model.Content</span>
    </div>
    <div class="col-xs-2">
        @string.Format("{0} {1}", Model.SendDate.ToShortDateString(), Model.SendDate.ToShortTimeString())
    </div>
</div>